model_list:
  # === OpenAI Direktzugriff ===
  - model_name: chatgpt
    litellm_params:
      model: gpt-4o
      api_base: https://api.openai.com/v1
      api_key: ${OPENAI_API_KEY}

  - model_name: gpt-3.5
    litellm_params:
      model: gpt-3.5-turbo
      api_base: https://api.openai.com/v1
      api_key: ${OPENAI_API_KEY}

  # === vLLM (GPU) ===
  - model_name: mistral-vllm
    litellm_params:
      model: mistralai/Mistral-7B-Instruct-v0.2
      api_base: http://vllm:8000/v1

  - model_name: llama3-vllm
    litellm_params:
      model: meta-llama/Meta-Llama-3-8B-Instruct
      api_base: http://vllm:8000/v1

  # === HuggingFace TGI (CPU) ===
  - model_name: mistral-tgi
    litellm_params:
      model: mistralai/Mistral-7B-Instruct-v0.2
      api_base: http://tgi:80/v1

  # === Ollama (JSON API-kompatibel) ===
  - model_name: llama3-ollama
    litellm_params:
      model: llama3
      api_base: http://ollama:11434
      model_info:
        mode: completion

