
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=mistral

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "${N8N_PORT}:5678"
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASS}
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - ollama

volumes:
  ollama-data:
  n8n-data:
