version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ${OLLAMA_DATA}:/root/.ollama
    environment:
      - OLLAMA_MODELS=${OLLAMA_MODELS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5

  vllm:
    image: vllm/vllm-openai:latest
    command: >
      python3 -m vllm.entrypoints.openai.api_server \
        --model ${VLLM_MODEL} \
        --host 0.0.0.0 \
        --port 8000
    ports:
      - "${VLLM_PORT}:8000"
    volumes:
      - ${VLLM_DATA}:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    build: ./gateway
    ports:
      - "${GATEWAY_PORT}:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - VLLM_URL=http://vllm:8000
    depends_on:
      ollama:
        condition: service_healthy
      vllm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  ollama_data:
  vllm_data:
