
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=mistral
    networks:
      - ai-net

  ollama-llama3:
    image: ollama/ollama
    container_name: ollama-llama3
    ports:
      - "11435:11434"
    volumes:
      - ollama-llama3-data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=llama3
    networks:
      - ai-net

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "${N8N_PORT}:5678"
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASS}
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - ollama
    networks:
      - ai-net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - ai-net

volumes:
  ollama-data:
  ollama-llama3-data:
  n8n-data:
  rag_documents:
  rag_storage:
  qdrant_data:

networks:
  ai-net: