
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=mistral
    networks:
      - ai-net

  #ollama-llama3:
  #  image: ollama/ollama
  #  container_name: ollama-llama3
  #  ports:
  #    - "11435:11434"
  #  volumes:
  #    - ollama-llama3-data:/root/.ollama
  #  restart: unless-stopped
  #  environment:
  #    - OLLAMA_MODELS=llama3
  #  networks:
  #    - ai-net

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "${N8N_PORT}:5678"
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASS}
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - ollama
    networks:
      - ai-net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - ai-net

  rag-backend:
    build:
      context: ./rag-backend
      dockerfile: ./rag-backend/Dockerfile
    # Du kannst die Zeile "image:" weglassen; mit build erstellt Compose lokal ein Image
    image: pmx/rag-backend:latest
    pull_policy: build
    container_name: rag-backend
    env_file:
      - ./rag-backend/.env
    environment:
      # Fallbacks, falls in .env nicht gesetzt
      RAG_BASE_PATH: /rag
      OLLAMA_BASE_URL: http://ollama:11434
      QDRANT_URL: http://qdrant:6333
    ports:
      - "8082:8082"
    volumes:
      - ./rag-backend/documents:/app/documents
      - ./rag-backend/storage:/app/storage
    depends_on:
      - ollama
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8082/rag/health"]
      interval: 20s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ai-net

volumes:
  ollama-data:
  ollama-llama3-data:
  n8n-data:
  rag_documents:
  rag_storage:
  qdrant_data:

networks:
  ai-net: