version: "3.9"
services:
  rag-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pmx/rag-backend:latest
    env_file:
      - .env
    networks:
      - pmx-net
    ports:
      - "8082:8082"
    depends_on:
      - ollama
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8082/rag/health"]
      interval: 20s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  pmx-net:
    external: true
