services:
  rag-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pmx/rag-backend:latest
    pull_policy: build        # <- wichtig: nicht aus Registry ziehen
    env_file:
      - ./.env    # <- .env-Pfad relativ zum Repo-Root
    networks:
      - ai-net
    ports:
      - "8082:8082"
    depends_on:
      - ollama
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8082/rag/health"]
      interval: 20s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  ai-net:
    external: true
